language: java
jdk:
   - oraclejdk8
addons:
   postgresql: "9.4"
sudo: required
before_script:
   - cp src/main/resources/travis_application.properties src/main/resources/application.properties
services:
   - postgresql
before_install:
   - chmod +x mvnw
   - psql -c "CREATE DATABASE testing_db;" -U postgres
branches:
   only:
   - test
deploy:
   provider: heroku
   api-key:
      secure: f2902d3a-43cf-48e0-aaa8-5def4c232846
   app: e1400487reactspring
   on:
        branch: test
